version: 2

jobs:

    test:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                tox tests/ -vv

    integrate:
        docker:
            - image: circleci/python:3.8
            - image: apachepulsar/pulsar:2.5.1
                #  TODO - copy local conf file to conf/ (which is adjacent to bin/)
              command: bin/pulsar standalone
        steps:
            - checkout
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0
            - run: dockerize -wait tcp://localhost:8080 -timeout 1m # Pulsar
            - run: dockerize -wait tcp://localhost:6650 -timeout 1m # Pulsar
            - run: |
                pip install --user tox
                tox integrate_tests/ -vv

    examples:
        docker:
            - image: circleci/python:3.8
            # - image: apachepulsar/pulsar:2.5.1
              # command: bin/pulsar standalone
        steps:
            - checkout
            - setup_remote_docker
                # Install via apk on alpine based images
            - run: |
                wget https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce-cli_20.10.7~3-0~debian-buster_amd64.deb
                sudo dpkg -i docker-ce-cli_20.10.7~3-0~debian-buster_amd64.deb
            - run:
                name: start pulsar-docker server with config file
                command: |
                   sudo docker build .circleci/images/testpulsar/ -t testpulsar
                   sudo docker run -d testpulsar
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0
            - run: dockerize -wait tcp://localhost:8080 -timeout 1m # Pulsar
            - run: dockerize -wait tcp://localhost:6650 -timeout 1m # Pulsar
            - run: |
                pip install --user tox
                tox --notest -vv
                . .tox/py/bin/activate
                ./examples/run.sh

    pycycle:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox pycycle
                tox --notest -vv
                . .tox/py/bin/activate
                pycycle --here --verbose


workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - integrate
            - examples
            - pycycle